import { Providers } from '@/providers'
import StyledComponentsRegistry from '@/utils/registry'
import { Inter } from 'next/font/google'
import PropTypes from 'prop-types'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio Dan Argolo',
  description: 'Generated by create next app',
  keywords: 'portfolio, software, developer, projects, frontend',
  author: 'Dan Argolo',
  icons: {
    icon: '/logo.svg',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Providers>
            {children}
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
}
